scrape_configs:
  - job_name: 'application_metrics'
    metrics_path: /actuator/prometheus
    scrape_interval: 1s
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/*.json
          - /etc/prometheus/targets/*.yml
          - /etc/prometheus/targets/*.yaml