{
 "title": "Refactoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "total" }
   ]
  },
  {
   "title": "Login Attempts Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "user_login_attempts_total", "legendFormat": "total" }
   ]
  },
  {
   "title": "HTTP Errors Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "http_requests_errors_total", "legendFormat": "total" }
   ]
  },
  {
   "title": "Database Query Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "db_queries_total", "legendFormat": "total" }
   ]
  },
  {
   "title": "HTTP Request Duration Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_max",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Database Query Duration Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "db_query_duration_seconds_max", "legendFormat": "max" }
   ]
  }
 ]
}